layout_spectrum: 0.6450861475675708
typography_spectrum: 0.9534178932898189
color:
  brandStrength: 0.21550719929425655
  lightness: 0.6244863949746521
  saturation: 0.0033309629583491546
  rhythmicContrast: 0.8177187239150933
  brandColors:
    - '#F2385A'
    - '#F5A503'
    - '#E9F1DF'
    - '#4AD9D9'
    - '#36B1BF'
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
name: zambranaproducciones
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2F6188t0ogOsE%3Ffeature%3Doembed&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3D6188t0ogOsE&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2F6188t0ogOsE%2Fhqdefault.jpg&key=a715cf41cc93453ca338d350cd26f87b&type=text%2Fhtml&schema=youtube"
      width="640" height="360" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      author:
        - name: Eduardo Ceregatti
          url: 'https://www.youtube.com/user/Chereizacion'
          avatar: {}
      related: []
      publisher:
        url: 'https://www.youtube.com/'
        name: YouTube
        favicon: 'https://s.ytimg.com/yts/img/favicon-vfl8qSV2F.ico'
        domain: youtu.be
      keywords:
        - fotos
        - cabecera web
      description: Video creado para exhibirse en una pagina web.
      '@type': VideoObject
      app_links:
        - url: 'vnd.youtube://www.youtube.com/watch?v=6188t0ogOsE&feature=applinks'
          type: ios
          namespace: ai
          app_store_id: '544007664'
          app_name: YouTube
        - url: 'vnd.youtube://www.youtube.com/watch?v=6188t0ogOsE&feature=applinks'
          type: android
          namespace: ai
          app_name: YouTube
          package: com.google.android.youtube
        - url: 'https://www.youtube.com/watch?v=6188t0ogOsE&feature=applinks'
          type: web
          namespace: ai
        - url: 'vnd.youtube://www.youtube.com/watch?v=6188t0ogOsE&feature=applinks'
          namespace: twitter
          type: ipad
          name: YouTube
          id: '544007664'
        - url: 'vnd.youtube://www.youtube.com/watch?v=6188t0ogOsE&feature=applinks'
          namespace: twitter
          type: iphone
          name: YouTube
          id: '544007664'
        - url: 'https://www.youtube.com/watch?v=6188t0ogOsE'
          namespace: twitter
          type: googleplay
          name: YouTube
          id: com.google.android.youtube
        - path: http/www.youtube.com/watch?v=6188t0ogOsE
          package: com.google.android.youtube
          namespace: google
          type: android
        - path: vnd.youtube/www.youtube.com/watch?v=6188t0ogOsE
          package: '544007664'
          namespace: google
          type: ios
      '@context': 'http://schema.org'
      isBasedOnUrl: 'https://youtu.be/6188t0ogOsE'
      title: Video cavecera
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
title: Zambrana Producciones
description: Empresa dedicada a la producciÃ³n de contenido audiovisual.
github: true
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/4920a240-21f7-465b-87fa-bbb98ca98e3e.png
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/9aa96582-e517-4ab2-b15f-8cfb3c5e226e.svg
author:
  name: Eduardo Ceregatti Madrigal
  email: ceregaster@gmail.com
